name: DRF_API_Query

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/data
  
  django:
    build: .  # Refer to next to .yml file
    container_name: django_app
    restart: always
    depends_on: # don't start django unless db exists
      - postgres  # service name
    volumes:
      - ./app:/app  # ./app next to yml map to /app inside container
    ports:
      - "8000:8000"
    command: >
      sh -c "
          if python manage.py shell -c 'from django.contrib.auth.models import User; print(User.objects.filter(username=\"admin\").exists())' | grep -q 'True'; then
            echo 'Admin user exists, skipping app and database setup';
          else
            if [ ! -f manage.py ]; then 
              django-admin startproject core .; 
            fi &&
            if [ ! -d inventory ]; then 
              python manage.py startapp inventory; 
            fi &&
            rm -f inventory/migrations/0001_initial.py &&
            python manage.py migrate &&
            python manage.py makemigrations &&
            python manage.py migrate inventory --fake &&
            python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin\");' ;
          fi &&
          python manage.py runserver 0.0.0.0:8000
        "
